# Configuração NGS DNASeq pipeline

THREADS: 20
# As amostras
SAMPLES:
  - 510-7-BRCA_S8_L001

OUTPUT_DIR: "output"

# Arquivos de Genoma de Referencia
reference:
    GENOME_DIR: "data/reference"
    GENOME_FASTA: "data/reference/hg19.fasta"
    TARGET_BED: "data/BRCA/BRCA.bed"
    SNPEFF_DATA: "/home/prospecmol/anaconda3/envs/DNASeq/share/snpeff-5.2-1/data"
    SNPEFF_GENOME: "hg19_custom"
    SNPEFF_PATH: "/home/prospecmol/anaconda3/envs/DNASeq/share/snpeff-5.2-1"

