name: DNASeq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - sed=4.9
  - fgbio-minimal=2.5.21
  - bedtools=2.31.1
  - snakemake
  - snakemake-wrapper-utils=0.7.2
  - snpeff=5.2
  - fastqc=0.12.1
  - fastp=1.0.1
  - bwa=0.7.19
  - samtools=1.22
  - picard-slim=3.4.0
  - freebayes=1.3.10
  - vcftools
  - vcflib=1.0.14
  - bcftools=1.22
  - htslib=1.22
  - parallel=20250622
  - tabix
  - snpeff=5.2
  - openjdk